from typing import Generator

def slugify(text: str) -> str: ...


class GenerateSearchResults:
    def __init__(self, search: str) -> None: ...
    def __repr__(self) -> str: ...
    def __iter__(self) -> Generator[str, None, None]: ...
    def __getitem__(self, index) -> list[str]: ...
