from typing import Any, Literal, Union

import pandas
from selenium.webdriver import Chrome, Edge

from google_comments.base import SpiderMixin

COMMENTS_SCROLL_ATTEMPTS: Literal[500]

FEED_SCROLL_ATTEMPTS: Literal[30]

COMMENTS_SCROLL_WAIT_TIME: Literal[10]


class GoogleMapsMixin(SpiderMixin):
    COMMENTS: list = ...
    collect_reviews: bool = ...
    keep_unique_file: bool = ...
    scrap_session_id: str = ...
    driver: Union[Chrome, Edge] = ...
    filename: str = ...
    is_loop: bool = ...
    seen_urls_outputted: bool = ...

    def __init__(
        self,
        output_folder: str = ..., 
        headless: bool = ...
    ) -> None: ...
    def __repr__(self) -> str: ...
    def __del__(self) -> None: ...
    def __hash__(self) -> str: ...

    def sort_comments(self) -> None: ...
    def flatten(self) -> list[dict[str, Any]]: ...
    def create_comments_dataframe(
        self, 
        *, 
        save: bool = ..., 
        columns: list[str] = ...
    ) -> pandas.DataFrame: ...

    def create_files(self, business, filename: str) -> None: ...


class GooglePlaces(GoogleMapsMixin):
    def get_dataframe(self) -> pandas.Dataframe: ...
    def start_spider(self, url: str) -> None: ...


class GooglePlace(GoogleMapsMixin):
    def start_spider(
        self, 
        url: str,
        comments_scroll_attempts: int = None,
        url_business_id: str = None,
        is_loop: bool = ...,
        maximize_window: bool = ...
    ) -> None: ...
    def iterate_urls(
        self,
        comments_scroll_attempts: int = None,
        urls: list[Union[str, dict[str, str]]] = ...
    ) -> None: ...
