import pathlib
from typing import Any, Literal, Union

import pandas
from selenium.webdriver import Chrome, Edge

from google_comments.base import SpiderMixin


class SearchLinks(SpiderMixin):
    URLS: list = ...
    confusion_pages: list = ...
    base_url: str = ...
    driver: Union[Edge, Chrome] = ...
    data_file: str = ...
    current_iteration: int = Literal[0]
    headless: bool = ...
    initial_data_file: str = ...
    output_filename: str = ...
    search_data_path: pathlib.Path = ...

    def create_file(self, prefix: str = ...) -> None: ...
    def before_launch(self) -> pandas.DataFrame: ...
    def start_spider(self, take_screenshots: bool = ...) -> None: ...


class SearchBusinesses(SearchLinks):
    collected_search: list = ...
    searches: list = ...

    def flatten(self) -> list[dict[str, Any]]: ...
